### ISSUE TITLE
No menu sound effects on boot

### ISSUE THREAD

**Issue by dVerge** [Aloshi/EmulationStation#130]
First, I just want to say a big thank you to everyone involved! I just finished converting a broken SNES to a fully functional retro gaming system with working controllers, power/reset switches, etc., and I couldn't have done it without piecing together all the hard work this community has put in.

So, everything is working great, except one minor annoyance:

When ES first loads up, the sound effects (e.g. menu scrolling, start game) do not play. The sounds will only play after launching an emulator, then quitting and returning to ES.

Any ideas? 

Thanks ahead!

**Comment by surtarso** [comment]
I have this same problem, navigation sounds only work after I enter a game than leave to ES.
I am on a PC tho, so I dont have a config.txt, also, im on a laptop so no HDMI input problem for me.
I DO get this after a fresh boot:
Feb 05 11:32:58 lvl2:    req sound [video.launch]
Feb 05 11:32:58 lvl2:      (missing)
But as stated... after I enter a game and go back to ES, the navigation sound magically works.

I am using my own theme, as follows
https://github.com/surtarso/es-theme-urcade
