### ISSUE TITLE
Has anyone tried porting to OS X?

### ISSUE THREAD

**Issue by swillis11** [Aloshi/EmulationStation#145]
I was going to attempt to build/port to OS X if no one has done this yet. I'm not sure how ambitious this is though.

Running Mavericks

**Comment by dishins** [comment]
Hi, i managed to Configure and Generate Aloshi's master branch and generate a Solution in XCODE, however im stuck with the following error when compiling to dmg inside xCode:

In: ThemeData.h, on the line:
class ThemeException : public std::exception

Im getting: "exception specification of overriding function is more lax than base version"

I've looking around and seems to have something to do with the way the exception is thrown. Any help on this?

**Comment by Aloshi** [comment]
I'm guessing you need to add `noexcept` to the `what()` method and possibly constructor (just add `noexcept` at the end of the method signatures, see [here](http://en.cppreference.com/w/cpp/language/noexcept)).

**Comment by dishins** [comment]
thx Aloshi, that worked. I'm struggling now with some "Expression Expected" errors but i think i can handle this. If anyone is interessed in trying this i can upload my xcode solution.

**Comment by jctwood** [comment]
I would be very interested!

**Comment by pasnox** [comment]
Just thrown a perfect OSX/Clang port here: https://github.com/Aloshi/EmulationStation/pull/478
No visual glitches, only VolumeControl is missing.

**Comment by displaced** [comment]
I had worked on this too - see #473

I think pasnox's is more correct than mine, but I did add a bit of code that hides dotfiles from the directory scanner.  My roms live on a network share which doesn't support HFS+ metadata, so OS X litters the directory with dotfiles containing that info.

**Comment by displaced** [comment]
I should probably add that I'm not particularly familiar with C++ so my code really was a case of 'hit it till it works'.

I had some luck getting cmake to generate an Xcode project. It'd be nice to get that into the project and get the build running so that it generates a neat .app bundle containing any referenced libraries which aren't present on OS X by default to help users just download and go.

**Comment by pasnox** [comment]
I guess it would be fine to be able to generate xcode project.
Creating a bundle is also possible for cmake, may add that later if needed.

**Comment by naga11284** [comment]
Hi.. 
I am struggling with the same issue mentioned by  "teknofile" commented on Dec 29, 2014.

Could someone help me to sort out the issue?
<img width="1165" alt="podofo_builderror" src="https://cloud.githubusercontent.com/assets/12047974/12011300/f379ac46-aced-11e5-97e6-861fd9c5287e.png">
