### ISSUE TITLE
Font bug on Windows 7

### ISSUE THREAD

**Issue by iNem0o** [Aloshi/EmulationStation#195]
Hi,

This is what i had when i launched ES on my fresh Windows 7 install

![untitled](https://cloud.githubusercontent.com/assets/1144755/3571136/dfc1666c-0b59-11e4-8dc8-037d43f6017e.png)

i tried to install DejaVu font on system but problems still there

i used http://emulationstation.org/downloads/releases/emulationstation_win32_latest.exe to install.

**Comment by McMoobud** [comment]
yup, updated drivers and it's sorted. 

Now I just need to clear an DLL issue :(
