### ISSUE TITLE
cmake hickup on Fedora with ${SDL2MAIN_LIBRARY}

### ISSUE THREAD

**Issue by npr77** [Aloshi/EmulationStation#205]
Just cloned your repo and tried to build the unstable branch. Installed all dependencies, but still SDL2MAIN_LIBRARY was set to NOTFOUND - even though all SDL2-devel packages were installed. I am new to cmake and cxx so I just tried the brute force approach: deleted the main lib reference and gave it a go.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 52354fb..be15b3e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -137,7 +137,6 @@ set(COMMON_LIBRARIES
     ${FREETYPE_LIBRARIES}
     ${FreeImage_LIBRARIES}
        ${SDL2_LIBRARY}
-    ${SDL2MAIN_LIBRARY}
     ${CURL_LIBRARIES}
     pugixml
     nanosvg
```

That's it. Simply removed ${SDL2MAIN_LIBRARY} and after that I could build the current unstable branch flawless and got a working executable. I don't know if even on other systems like Windoze or Ubuntu this lib ref is superfluous as well as you already include SDL2_LIBRARY - seems to be enough on Fedora 20 :)

**Comment by enodr** [comment]
This commit breaks windows build (tested with Visual Studio 2010) with error:
MSVCRT.lib(crtexew.obj) : error LNK2019: unresolved external symbol _WinMain@16 referenced in function ___tmainCRTStartup
Adding back SDL2main.lib in libs solves the problem.
