### ISSUE TITLE
Menu Sounds

### ISSUE THREAD

**Issue by Aloshi** [Aloshi/EmulationStation#21]
I'm going to start working on adding some simple menu sounds next.

I'll be using the SDL_mixer library instead of the standard SDL audio functions (because the standard SDL audio functions don't support playing multiple sounds at once).

I'll be testing with WAV files, at least for now. The SDL_mixer library looks like it supports OGG and MP3, but I'm not sure if you need to include any extra libraries to set them up.

**Comment by gnunezrocha** [comment]
How to set select/ok sound?
