### ISSUE TITLE
[ES 2] No gamepad input when started via startx

### ISSUE THREAD

**Issue by leuprechtroman** [Aloshi/EmulationStation#223]
When I start ES with "startx /usr/bin/emulationstation" the only thing I can do is close ES via pressing F4. This is not a general problem of X, since Retroarch accepts gamepad/keyboard input when launched via "startx".

When ES is launched via Window Manager(fluxbox) input works, too.
Platform: Arch Linux, Arch: x64

Anyone experienced the same problem?

**Comment by DocMAX** [comment]
any updates? 3 years and not fixed?

**Comment by pokevania** [comment]
7 years and no solution even though a raspberrypi will do exactly this but correctly.
