### ISSUE TITLE
Fails to start on raspberry pi

### ISSUE THREAD

**Issue by pulb** [Aloshi/EmulationStation#264]
If if I try to start emulationstation unstable on my raspberry pi (arch linux) I get the following error:

lvl0: Error initializing SDL!
No available video device
lvl0: Renderer failed to initialize!
lvl0: Window failed to initialize!

I used this recipe to build it:
https://aur.archlinux.org/packages/em/emulationstation-git-unstable/PKGBUILD

**Comment by pietrondo** [comment]
same problem with raspberry2 on archlinux and pkgbuild of sdl with egl of pulb

**Comment by ignaciohita** [comment]
Please pulb, can you give us some steps to fix this problem? I can see what you did but I don't know how to make it work in my Raspberry since I'm a newie.

Thanks!

**Comment by pulb** [comment]
@ignaciohita: you have to compile [this](https://aur.archlinux.org/packages/sdl2-opengles/) package on your raspberry pi using [this](https://wiki.archlinux.org/index.php/Makepkg) method.
