### ISSUE TITLE
ES2 crash upon exit (windows)

### ISSUE THREAD

**Issue by keltoigael** [Aloshi/EmulationStation#279]
Hello all, new here and new to ES. I just installed and set it up on 3 PC's and all 3 PC's have the same crash on exit. When you go quit emulationstation, it closes the main window of ES and leaves the command line box in the background and after about 10 seconds gives the unresponsive typical windows crash. Is this common? I found it strange I have 3 different set up's that are all doing the same thing. When this happens I loose all my personal game ratings in the process.

**Comment by nilsbyte** [comment]
With the database update to SQLite saving the data should be instant, so this problem will be solved soon.
