### ISSUE TITLE
Launching back into the Emulation Station taking a long time on Rpi

### ISSUE THREAD

**Issue by Cheaves** [Aloshi/EmulationStation#283]
Loading back into the UI after launching the emulator on my Rpi is very slow. Specifically when I have a theme setup. I'm running a Rpi Model B 512Mb using a 16gb ScanDisk SDHC card.

I've created a custom theme but it takes up-to 25 seconds to reload it every-time I relaunch the front-end. If I remove the theme and revert back to the embedded assets it's pretty much instant. I'm fairly sure its the file I/O that's the issue since all the texture files are ditched and reloaded each time.

I'm proposing a method (currently working on the fix) to keep regularly reloaded file data in memory whilst the emulators run. This will reduce the costly I/O and memory allocation functions. It works much like the embedded data in that it keeps file data in a globalRes map and first checks this for any valid data before attempting a fresh load. This data is then free'd upon a full theme change.

Its a trade off of course but should help those low powered devices that have some memory to spare. Please let me know if anybody is interested in such a feature.

Thanks

**Comment by nilsbyte** [comment]
Right, @Aloshi  :) Additionally, the switch to the SQLite database for meta data should speed up the return to ES after quitting a game.

**Comment by Enverex** [comment]
Nils: Has sqlite been implemented now then or are you closing this as a duplicate?
