### ISSUE TITLE
GUI displays white background and gray boxes for text

### ISSUE THREAD

**Issue by Jcloud9** [Aloshi/EmulationStation#305]
System: Win 7 64 bit 2GB ram/ Core2 duo/ Geforce9800 GPU.  Setup using retroarch & cores.   When I run the application the GUI displays white background and gray boxes for text.  I can interact with it blindly, as I learned from looking at the log file showing I was mapping my keyboard.   I followed the instructions on this video https://www.youtube.com/watch?v=eLlWfgLvG64  and used the config file provided by the video uploader.

**Comment by nilsbyte** [comment]
Your graphics card does not support the version of OpenGL EmulationStation needs. Which graphics card do you have?

**Comment by RandomAdjectives** [comment]
Same problem, GeForce GTX 1070, fully updated drivers from GeForce Experience, 391.35.
