### ISSUE TITLE
"loading..." lasting for 15 seconds or more

### ISSUE THREAD

**Issue by nitrofurano** [Aloshi/EmulationStation#313]
as far as i'm adding more systems, the "loading..." part during EmulationStation boot seems to start lasting longer and longer - is that any option that allows us to see what exactly EmulationStation is loading, so this loading process would look less boring?

or, as well, i guess there should be some kind of "reload/rescan" option internally (or also via some key pressing on booting), that perhaps would allow a faster booting?

**Comment by nilsbyte** [comment]
Yep, the more platforms/systems you have set up, the longer the loading of ES takes, depending on the total number of games.

**Comment by ian57** [comment]
WIth my distro containing more than 4000 roms.... it takes mores than 1 minute to display the emu menu with ES2. This is not the case with ES1. Does ES2 verify the gamelists.xml files before while loading. It is possible to avoid this checking?
