### ISSUE TITLE
Suggestion: Vertical/Grid home screens view

### ISSUE THREAD

**Issue by ProfessorKaos64** [Aloshi/EmulationStation#319]
I apologize if this was already suggested. This would make having 20+ systems easier to locate for me. Just a suggestion. Thank you for the great software! I am evaluating this as a front end for my RetroRig project that uses XBMC at the moment.

-PK

**Comment by nilsbyte** [comment]
The carousel for selecting platforms is set. We won't change this layout, but we are planning a grid view for the games list where one item in the grid represents one game.
