### ISSUE TITLE
Update files on website

### ISSUE THREAD

**Issue by RJSzynal** [Aloshi/EmulationStation#320]
When using the shutdown option in windows it tries to run the linux command 'sudo shutdown now' instead of the windows command 'shutdown -s -t 0'. I haven't checked reboot but I presume it's the same.
When I get some time I might fork the project and have a look at a few of the issues I've noticed including this one. I'd need to polish up on my C first though.

**Comment by nilsbyte** [comment]
@Aloshi can you update the files on the website?

**Comment by RJSzynal** [comment]
Seen these are updated now.
Thanks guys
