### ISSUE TITLE
EmulationStation freezes with white or black screen (on start)

### ISSUE THREAD

**Issue by patrick500** [Aloshi/EmulationStation#330]
Hi,
I have got an issue with EMULATIONSTATION on raspberry b+.

When I use HDMI output on rapsberry with a DVI cable connected to my TV-HD/Computer-Screen, there is no issue. (=cable: HDMI-DVI)
 When I use HDMI output on rapsberry with a HDMI cable connected to my TV, I have got an issue. (=cable HDMI-HDMI)
 
The soft configuration is exactly the same (no change, just change the cable to appear the issue on my raspberry).
 I have tested several HDMI-HDMI cables, and it’s the same issue. So no impact with different HDMI-HDMI cables.
 I have tested several TV-HD ans it’s the same issue.
 
Issue description (only with HDMI-HDMI cable):
 The raspberry starts normally. EmulationStation is loading, but at the end of the load, I have got a white screen or a black screen. The emulationStation menu doesn’t appear.
 
I have read the forum/issues and I have tried to rename some ROMS folders.
 When some ROMS folder are missing, the issue disapears. That means everything works well on my TV with the HDMI-HDMI cable.
 When I remane those folders with the original name, the issue appears again.
 I have tried to recreate one of those folders and transfer the rom files to the new folder, but the issue appears again (with the HDMI cable).
 
I can understand that the fact to change the cable, my TV-HD switchs the screen’s resolution.
 
Have you got an idea about the solution? (and why does EmulationStation seem to "dislike" some roms folders, only when HDMI cable is used).
 Has someone already solved a similar issue with EmulationStation on PI B+? 

thanks a lot for your help.
Patrick.

**Comment by Aloshi** [comment]
You probably don't have enough memory allocated to the GPU for the higher resolution the Pi uses when connected over HDMI.  You can try adding more by using `sudo raspi-config` or editing `/boot/config.txt`'s `gpu_mem` line by hand (you'll probably need to `sudo` your text editor).  Removing any systems you don't want will also help.

**Comment by patrick500** [comment]
Hi Aloshi,
about my config : 
arm_freq=1050
gpu_mem_512=384
core_freq=500
sdram_freq=550
over_voltage=6
Do you think I can increase a parameter ?

About systems to be removed, I will test.

**Comment by patrick500** [comment]
Hi Aloshi,
you are right !
I have removed some systems (rename the roms folder of some systems) and EmulationStation works  using HDMI-HDMI cable.
Fortunately, all of my wanted systems are kept... :)

I hope it will be corrected in a next release of EmulationStation or Rapberry ;)

I thank you very much for your help.
