### ISSUE TITLE
Looking for advice creating title images / themes

### ISSUE THREAD

**Issue by ProfessorKaos64** [Aloshi/EmulationStation#332]
Hi, I started an emulationstation flavor of my [RetroRig](https://github.com/ProfessorKaos64/RetroRig) project called "[RetroRig-ES](https://github.com/ProfessorKaos64/RetroRig-ES)" using your front end. I was wondering how I can get started filling some missing gaps in [systems missing](https://github.com/ProfessorKaos64/RetroRig-ES/issues/3)? Very much appreciate the work and hope to contribute in the future to the repo here.

* Playstation 2
* Nintendo Wii
* Atari Lynx
* Neo Geo CDZ
* PSP (Playstation Portable)

I noted under /etc/emulationstation/themes/simple/pcengine, there is a main XML file and SVG files for the pieces. Maybe I can figure this out, but if you have any pointers or a forum, that should help. I am so-so with GIMP, and I probably could at least fix up images for the main screen.

I made a copy of the psx theme folder, added a new ps2 image in svg format and altered the xml file. Current example is here: [link](http://www.libregeek.org/temp_dl/ps2.tar.gz). If I use it, I just get a segfault.

**Comment by nilsbyte** [comment]
PS2, Wii and PSP are already there, just look at my blog to grab the latest version: http://blog.nilsbyte.de/downloads/

I will add the Atari Lynx and Neo Geo CDZ in a future release. Thanks!

**Comment by ProfessorKaos64** [comment]
@nilsbyte , thank you very very much. Can I inject these theme files into the simple theme with the rest? CDZ is a nice one to support. I tried to alter an existing themse with inkscape (for SVG files), but it would just segfault. I actually wouldn't mind making the title banners for the main screen, even if just for my self. In any case, your help is appreciated. Take care.

-pk

**Comment by nilsbyte** [comment]
I am the creator of the official stock theme, so... yes, it's always the most recent version on my blog :)

Inkscape is not very good. Try Adobe Illustrator for vector editing.

**Comment by ProfessorKaos64** [comment]
I'll just be patient for new themes. Is an issues ticket the way to request new themes? I know I am missing ones yet for VirtualBoy, Wonderswan, Wonderswan Color, and the aforementioned Neo Geo AES/CDZ.  Great job on the ScummVM title! I love that one.

**Comment by nilsbyte** [comment]
Thanks :) I have added all mentioned platforms to my TODO list. I can't say when they are done. The easiest way to request new platforms in the theme would be the contact form on my blog. But you can also post it here, it will only take longer for me to notice :)
