### ISSUE TITLE
Scraper: Use already saved images, just scrape metadata

### ISSUE THREAD

**Issue by robertybob** [Aloshi/EmulationStation#335]
Hi,

I have 750 NES roms with images named the same (e.g.  1942.nes and 1942.jpg). I've just run the scraper and it's creating a new image 1942-image.jpg in a folder called downloaded_images.

1) how do I tell the scraper to not download an image if one already exists
2) if by chance I didn't have a corresponding image, how do I tell the scraper not to save it in the downloaded_images folder and to save it alongside the rom

Is either of the above possible?

**Comment by nilsbyte** [comment]
1) You can't. The scraper downloads the image every time you are scraping a platform
2) The destination folder for the meta data box art is fixed. It will stay like that to maintain a clear structure.

**Comment by robertybob** [comment]
The thing is, I don't want it to skip downloading the description etc. , I literally only want it not to download the image - I've spent absolutely ages sourcing decent-quality boxart images. 
There's no way of having an option so 'if image found, check metadata - if missing, only download metadata' ?

**Comment by nilsbyte** [comment]
As you can see by yourself, no. Sorry. 

An option to only download the missing part of meta data would be helpful in this case. 

@Aloshi, what do you think? Is this possible with a kind of checking routine which information to download?

**Comment by scar45** [comment]
I'm actually in the same situation as @robertybob right now. Can't appear to find any type of workaround. 

Consider this a +1 from me at the very least I suppose. Subscribing to this issue, and willing to test/cherry-pick any new commits!

**Comment by robertybob** [comment]
@scar45 I have a long-winded workaround if you're interested. I run ES on my RasPi but use my Windows PC to generate the XML file:

1) In the folder where my NES (for example) ROMs are, make an 'images' folder
2) Put all the boxart I've downloaded into that 'images' folder
3) Use Bulk Rename Utility to suffix '-image' to the artwork
4) Using github.com/sselph/scraper , put Scraper.exe into my ROM's folder and run Scraper.exe
5) If the scraper finds a game and an image exists in the 'images', it'll download the metadata and create an image suffixed -thumb
6) Once the scraper has finished, put images suffixed -thumb into ROM folder and delete all that have corresponding ROM file. This is the easiest way to work out whether the scraper has missed any game - i.e. if no -thumb image exists for a ROM, the game wasn't scraped and you'll have to add it manually.
7) Delete -thumb images
8) Using WinSCP or Filezilla, transfer ROMs to Pi and artwork from 'images' folder to correct folder on Pi
9) Put the generated gamelist.xml file in correct folder on Pi
10) Open the gamelist.xml file and using Find & Replace, edit it to link images to correct folder


and I've done this for my NES, SNES, MegaDrive, Master System, Sega 32x ROMs.

**Comment by scar45** [comment]
Thanks a bunch @robertybob! I have already batch renamed my images to append '-image' to the filename, so I'm set there, but I was unaware that there exists a Windows scraper which will generate ES-friendly gamelist.xmls. #6 is a nice tip as well for optimizing this process.

I will be giving it a shot as soon as I am home from work. Cheers and thanks again!

**Comment by scar45** [comment]
@robertybob I just came across this thread again and realized I hadn't confirmed that your method above worked great for me. Cheers!

@changetip grab him a beer, will ya?

**Comment by changetip** [comment]
Hi @robertybob, @scar45 sent you a Bitcoin tip worth a beer (22,151 bits/$5.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/730017)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by robertybob** [comment]
@scar45 Dude, that Bitcoin's now worth over $300 , I love you!!

**Comment by Kamikaze01git** [comment]
0,022151 BTC are now ~2100 USD ;-)
