### ISSUE TITLE
[Gamelist]

### ISSUE THREAD

**Issue by kasperrt** [Aloshi/EmulationStation#338]
When I scrape, the results appear, but when I exit the EmulationStation it resets, and its like I've never scraped at all.

In the console I got this
```
lvl0: 	Error saving gamelist.xml to ""/home/slottet/.emulationstation/gamelists/snes/gamelist.xml"" (for system snes)!
lvl0: 	Error saving gamelist.xml to ""/home/slottet/.emulationstation/gamelists/n64/gamelist.xml"" (for system n64)!
lvl0: 	Error saving gamelist.xml to ""/home/slottet/.emulationstation/gamelists/nes/gamelist.xml"" (for system nes)!
```

Any way of fixing this?

**Comment by nilsbyte** [comment]
Did you check the permissions of the `/home/slottet/.emulationstation/gamelists/` and its containing folders? Its likely to be the issue here.

**Comment by kasperrt** [comment]
Yeah, thanks :)

**Comment by dips52** [comment]
Guys I don't know what I was doing I allowed root access via ssh and then added a theme to the folder. When I rebooted RSP it came up with this error message about saving game list. Now all my scrapes have been removed and it keeps coming up with this error! Can you help me figure out if I lost all my scrapes and how to grant access to that directory (I can't see that folder through WINSCP, it must be hidden not sure how to make visible!)

Any help would be great here!

**Comment by dips52** [comment]
Found solution: 

http://blog.petrockblock.com/forums/topic/fix-no-gamelist-node-found-in-gamelist-xml-error-scraper-data-not-saved/
