### ISSUE TITLE
Frozen at welcome screen

### ISSUE THREAD

**Issue by latortuga** [Aloshi/EmulationStation#339]
Sorry if this is the wrong place to post this.

I am running emulationstation via the retropie project on my raspberry pi. I am using the latest image from RetroPie's site, v 2.3 (sorry, I'm not sure what version of emulationstation it includes). My Pi boots fine and gets to the Welcome screen, shows "No Gamepads detected" and is frozen - it does not respond to keyboard input at all. I know that my connected keyboard is working because I can press keys during the boot sequence and they appear at the command line. I've tested my SD card for corruption using h2testw and found no issues. I've even tried re-flashing the image several times and I always get a frozen screen at the Welcome screen.

Any ideas what might cause this? Troubleshooting ideas?

**Comment by expandables2** [comment]
Did you hold down a button so emulationstation can recognize the key input?

**Comment by latortuga** [comment]
Yes, nothing happens. I downloaded the beta 2.4 image and I'm getting the same behavior except, maybe 15-20% of the times that I boot my pi, it **does** recognize the keyboard and responds to F4. I tried again just now, held a key for quite awhile (30 seconds or more?) and no response. Given that the failure is happening intermittently, do you think this could be an issue with my pi?

**Comment by expandables2** [comment]
Did you try with a different sd card?

**Comment by latortuga** [comment]
I only have the one at the moment but I'll order another and give it another try and let you know if it changes anything.

**Comment by latortuga** [comment]
The problem ended up being my power cable/plug. I did not test for sure but I tried a different one and it works fine. I'm guessing it wasn't supplying a good 5V. Lesson learned, use a good power cable/block!
