### ISSUE TITLE
CLI --scrape

### ISSUE THREAD

**Issue by parkerlreed** [Aloshi/EmulationStation#342]
Why have this work up until the very end and then have "ACTUALLY THIS IS STILL TODO"?

The GUI scraper is very slow to download and load thumbnails. For 1000+ games it takes forever. I tried the cli thinking it would be faster. I would understand if --scrape exited with a TODO note but to have it prompt for the options then say TODO seems stupid.

**Comment by Aloshi** [comment]
Because it used to work and then it broke and I never fixed it because no one ever used it.  It's been removed on the branch I am currently working on.
