### ISSUE TITLE
Feature Request: Sort games by letter

### ISSUE THREAD

**Issue by ProfessorKaos64** [Aloshi/EmulationStation#343]
This is one feature I missed from my other project I have with XBMC+Rom Collection Browser, is the ability to sort games by chosen letter. Those of us with massive ROM collections would very much appreciate it. I apologize if this was already requested, I didn't see a ticket for it. A simple enough workaround, is to put lettered folders up one level from the ROMs, but can be tedious for existing collections. Keep up the great work!

-pk

**Comment by Aloshi** [comment]
The latest version already has a "jump to letter" function the "options" menu (press select on the game list).

**Comment by ProfessorKaos64** [comment]
Whoops, I'm sorry Aloshi. I'll close this.
