### ISSUE TITLE
sdl2 build instructions for rpi

### ISSUE THREAD

**Issue by joolswills** [Aloshi/EmulationStation#347]
on http://emulationstation.org/gettingstarted.html#install_rpi_standalone

instead of just ./configure for sdl2 it would be better as

./configure --disable-video-opengl

if the user has previously installed sdl1.x development libraries from raspbian, it will have installed the opengl headers/libs and it seems SDL2 on the pi if built with opengl chooses that before gles

**Comment by nilsbyte** [comment]
This info is more useful over at the GitHub page of this thing called RetroPie :-1: 

https://github.com/petrockblog/RetroPie-Setup/issues

**Comment by joolswills** [comment]
Why is that ? It is the emulation station site with the info that needs correcting - retropie package already handles compile options for SDL2 (and has a ready built binary). Actually the reason I opened the ticket was a user came over to our issue tracker asking for help following your install instructions and I noticed this issue :)

**Comment by nilsbyte** [comment]
Oh, sorry, my fault. I must have skipped the beginning of your post. @Aloshi, you should correct that information on the website.

**Comment by joolswills** [comment]
np :)

**Comment by Aloshi** [comment]
Updated, thanks for the heads up!
