### ISSUE TITLE
No delete files

### ISSUE THREAD

**Issue by fausto4ever** [Aloshi/EmulationStation#351]
I choose delete metada de a GC Game and delete the file no recover posible, please I suggest cancel this function.

**Comment by nilsbyte** [comment]
You should read carefully. The DELETE button is not for deleting meta data, it's for deleting the entire game file (ROM). There is even a confirmation!! See: http://i.imgur.com/bYt81df.png

Why should anybody want to delete just the meta data? If it's the wrong meta data, you can scrape this single game again with the SCRAPE button in the meta data editor.
