### ISSUE TITLE
Crashes while scraping images

### ISSUE THREAD

**Issue by digitalLumberjack** [Aloshi/EmulationStation#352]
Emulationstation runs out of memory and crashes after scraping for about 20 minutes, seems to depend on the images though how long it takes, but if you start scraping and have a terminal open and run free every once in a while you will see how the memory is slowly being eaten up until it finally crashes.

**Comment by Enverex** [comment]
How much RAM do you have and how many files is it trying to scan?

**Comment by sselph** [comment]
Which scraper were you using?

**Comment by digitalLumberjack** [comment]
Hi, I have 256mo of ram on my rpi, and i'm scanning a directory of 500 files. It stops around 200th file.
