### ISSUE TITLE
GamesDBShaScraper hash_path

### ISSUE THREAD

**Issue by GregHolmes** [Aloshi/EmulationStation#356]
on make, I'm getting this issue. I've attempted to search for any reference online but can't find anything. I'm running stock raspbian and attempting to install emulationstation. Could anyone shed some light on this issue please?

[ 73%] Building CXX object es-app/CMakeFiles/emulationstation.dir/src/scrapers/GamesDBShaScraper.cpp.o
/home/pi/EmulationStation/es-app/src/scrapers/GamesDBShaScraper.cpp: In function ‘boost::filesystem3::path GamesDBShaScraper::get_hash_path()’:
/home/pi/EmulationStation/es-app/src/scrapers/GamesDBShaScraper.cpp:25:15: error: no match for ‘operator+=’ in ‘hash_path += "hash.tsv"’
es-app/CMakeFiles/emulationstation.dir/build.make:606: recipe for target 'es-app/CMakeFiles/emulationstation.dir/src/scrapers/GamesDBShaScraper.cpp.o' failed
make[2]: *** [es-app/CMakeFiles/emulationstation.dir/src/scrapers/GamesDBShaScraper.cpp.o] Error 1
CMakeFiles/Makefile2:246: recipe for target 'es-app/CMakeFiles/emulationstation.dir/all' failed
make[1]: *** [es-app/CMakeFiles/emulationstation.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aloshi** [comment]
Interesting, it looks like the overloaded "+=" operator for boost::filesystem::path isn't working for some reason. Try changing [line 23](https://github.com/Aloshi/EmulationStation/blob/unstable/es-app/src/scrapers/GamesDBShaScraper.cpp#L23) of es-app/src/scrapers/GamesDBShaScraper.cpp to

```cpp
boost::filesystem::path hash_path = home + "/.emulationstation/rom_hashes/";
```

and line 25 to

```cpp
hash_path = hash_path / "hash.tsv";
```
and see if that compiles.

**Comment by GregHolmes** [comment]
Thank you!

Altering line 25 to your suggestion resolved the issue. Line 23 was identical to what I had in the file.
