### ISSUE TITLE
New Forum Not Sending Verification Emails

### ISSUE THREAD

**Issue by Enverex** [Aloshi/EmulationStation#358]
I signed up to the forum about 15 minutes ago and have re-requested the verification email several times but it looks like the forum isn't sending it.

I've checked my mail-server's logs and it's not being rejected, it doesn't seem to even be reaching my server which implies it's not being sent out in the first place.

Possibly something to look into as user's can't post till they've verified.

**Comment by Aloshi** [comment]
Nils noticed this, which is why I haven't been more public about the new forum (surprise: there is a new forum). I have the forum set to use sendmail but it doesn't seem to be working for some reason and my web host has been busy with work. Hopefully we can get this sorted out this weekend.

**Comment by Enverex** [comment]
Ah glad it's a known issue and not some weird quirk then. Let me know if you'd like me to look at it as I'd be happy to help.

**Comment by Aloshi** [comment]
Hopefully fixed now. I also installed some more anti-spam measures since I saw a lot of bots were registering. I also deleted all existing accounts because of said bots, so you'll have to re-register (sorry!).
