### ISSUE TITLE
App uses 100% of cpu core

### ISSUE THREAD

**Issue by enodr** [Aloshi/EmulationStation#359]
The rendering loop is not caped to 60 FPS so it tries to render as many frames as possible and thus eats all CPU (one core on windows). 

Here is a quick patch to limit UI to 60 fps (in main loop):

      int curTime = SDL_GetTicks();
      int deltaTime = curTime - lastTime;
      if (deltaTime < 1000/60) // cap to 60 fps
      {
         SDL_Delay(1);
         continue;
      }
      //int curTime = SDL_GetTicks();
      //int deltaTime = curTime - lastTime;
      lastTime = curTime;

**Comment by Aloshi** [comment]
The latest version of ES enables vsync by default, which takes care of this problem (and using better resolution timers than SDL_GetTicks()).
