### ISSUE TITLE
Scraping hangs

### ISSUE THREAD

**Issue by kruuth** [Aloshi/EmulationStation#362]
When I try to scrape game information the scraper tends to hang around game 100.  Ex.  I started scraping the Sega Mega Drive at about 9pm last night and when I came back this morning, it was sitting on game 135 of around 500.  The first move at about 10 secs each, but then later they seem to take up to 30 minutes per scrape.  When I end the scrape and start again, it starts up fine.

**Comment by sselph** [comment]
Which scraper were you using?
