### ISSUE TITLE
I know I am a fool, but I need some help. (Game installation issues)

### ISSUE THREAD

**Issue by dead-alus** [Aloshi/EmulationStation#364]
Hi guys and gals, any help would be appreciated.

I installed EmulationStation on my Raspberry Pi, but I am unable to use the RetroPie build because I only have one SD card to use and I am strapped for cash. I had to use the standalone install. 

The installation went well and the program functions, but I can't figure out where to put the games. I can't find an obvious folder for it. Can someone please end my misery?

Thanks!

**Comment by Enverex** [comment]
You create a systems file and then you put the games whereever you've specified they are.

See the "Configuring" section here - http://emulationstation.org/gettingstarted.html
