### ISSUE TITLE
Background sound emulationstation

### ISSUE THREAD

**Issue by expandables2** [Aloshi/EmulationStation#366]
Hi is there a way i can add background sound to emulationstation version 1? I see u have scroll sound and select sound is there a way i can edit the code to have background sound thanks.

**Comment by expandables2** [comment]
Any reply please

**Comment by expandables2** [comment]
:(

**Comment by Enverex** [comment]
No, and you know this as you already responded to an already-open issue ticket about this same thing - https://github.com/Aloshi/EmulationStation/issues/341

Don't open duplicate tickets, it just wastes people's time.

**Comment by expandables2** [comment]
I meant the old versin and i was asking how can i be able to do it

**Comment by expandables2** [comment]
I am asking how can i be able to develop version 1 of emulation station to have background sound. Since it is open source it should be able to am guessing.

**Comment by Enverex** [comment]
It's not a simple task, you'd have to find the source code for the old version, learn how it all works and then code in the relevant work to get audio in the places you're looking for. No-one's going to be able to hand-hold you through it though as that would take as much time as coding it in.

**Comment by expandables2** [comment]
Many people still use version 1.0 i am sure with aloshi skills he can add background sound  in less than  an hour since he wrote the code.

**Comment by nilsbyte** [comment]
@expandables2: 1.0 is not supported any longer, you should update to 2.0

Please :)

**Comment by expandables2** [comment]
I feel 1.0 suits me that is why i don't want to upgrade :(
