### ISSUE TITLE
Raspberry Pi 2 B - ft2build.h missing?

### ISSUE THREAD

**Issue by GregHolmes** [Aloshi/EmulationStation#387]
I've tried installing this on my new Pi 2, but first got the issue of Freetype being missing. Which I could solve by a previous issue found on here. However now, during make I get:

[  3%] Building CXX object es-core/CMakeFiles/es-core.dir/src/AudioManager.cpp.o
[  3%] Building CXX object es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o
In file included from /home/pi/EmulationStation/es-core/src/Window.h:5:0,
                 from /home/pi/EmulationStation/es-core/src/GuiComponent.cpp:2:
/home/pi/EmulationStation/es-core/src/resources/Font.h:6:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
es-core/CMakeFiles/es-core.dir/build.make:77: recipe for target 'es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o' failed
make[2]: *** [es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o] Error 1
CMakeFiles/Makefile2:194: recipe for target 'es-core/CMakeFiles/es-core.dir/all' failed
make[1]: *** [es-core/CMakeFiles/es-core.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Aloshi** [comment]
Try the solution listed in #384, namely run cmake with:

`cmake . -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype/ -DCMAKE_CXX_COMPILER=g++-4.7`

**Comment by GregHolmes** [comment]
Thank you for your reply!
The issue is when I run make. I found the cmake issue and ran that, got it to complete successfully. But when.I run make immediately after I get the above error.

**Comment by DZHOYER** [comment]
I got this same issue too, after running: 

cmake . -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype/ -DCMAKE_CXX_COMPILER=g++-4.7

And then running:

make

I get:

Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by binaryangel0100** [comment]
![dsc_0008](https://cloud.githubusercontent.com/assets/10982928/6180412/67b84ad0-b31c-11e4-8c3d-050937907694.JPG)

**Comment by binaryangel0100** [comment]
I've also had the same error as GregHolmes

"[ 3%] Building CXX object es-core/CMakeFiles/es-core.dir/src/AudioManager.cpp.o
[ 3%] Building CXX object es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o
In file included from /home/pi/EmulationStation/es-core/src/Window.h:5:0,
from /home/pi/EmulationStation/es-core/src/GuiComponent.cpp:2:
/home/pi/EmulationStation/es-core/src/resources/Font.h:6:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
es-core/CMakeFiles/es-core.dir/build.make:77: recipe for target 'es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o' failed
make[2]: *** [es-core/CMakeFiles/es-core.dir/src/GuiComponent.cpp.o] Error 1
CMakeFiles/Makefile2:194: recipe for target 'es-core/CMakeFiles/es-core.dir/all' failed
make[1]: *** [es-core/CMakeFiles/es-core.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2"

**Comment by Jcw87** [comment]
The solution that worked for me was using this:
cmake -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/

Notice it says freetype2, not freetype.

**Comment by GregHolmes** [comment]
freetype2 was the solution! thank you!

**Comment by mrturcot** [comment]
This was mine:

cmake . -DCMAKE_CXX_COMPILER=g++-4.7 -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/
