### ISSUE TITLE
How Do Folders work in gamelist.xml?

### ISSUE THREAD

**Issue by maddox** [Aloshi/EmulationStation#390]
I've read and re-read the docs on `gamelist.xml`, but It's not very clear what the structured XML should be for adding folders.The example gamelist doesn't show `folder` nodes.

In the listed elements of `folder`, the docs don't report a path, or anything like that.

So if I was writing a gamelist by hand, and wanted to add folders, how exactly does it work? How do I tell ES which games I want in that folder? Does it just look in the folder for another `gamelist.xml` file? Does it assume the path is `$current_system/$folder.title`?

I'm super lost in exactly how any of the folder stuff works, and googling `folder` with `emulation station` or `gamelist.xml` has proven brutal, lol. Thanks for any help!

**Comment by Aloshi** [comment]
The `<folder>` tags in the gamelist.xml basically let you style the folder gamelist entries that ES was going to create anyways. The path element is just the path to the folder. The contents of the folder will exactly mirror the file system (right now, anyway).
