### ISSUE TITLE
Spaces break Dolphin on Win64

### ISSUE THREAD

**Issue by kkjdroid** [Aloshi/EmulationStation#396]
<command>D:\Games\Emulated\Gamecube\Emulator\Dolphin.exe /b /e %ROM%</command>

This line launches Dolphin, but Dolphin sees two parameters, "Alien" and "Hominid.gcz"

<command>D:\Games\Emulated\Gamecube\Emulator\Dolphin.exe /b /e "%ROM%"</command>

This line launches Dolphin, but Dolphin sees one parameter, "Alien\ Hominid.gcz"

Neither line launches the ROM. The setup that I have does work with the one ROM I have that has no spaces (Pikmin).

**Comment by kkjdroid** [comment]
The same thing happens with SNES9x. EarthBound launches fine, Donkey Kong Country does not.

**Comment by MongoBongo** [comment]
Same thing happened to me, But I just used Bulk Rename Utility to replace all spaces with underscores. I know its not a "fix" but i found it the quickest way.

**Comment by kkjdroid** [comment]
Well, I could do that, but I'd rather have them named properly. I guess that's a solid plan B.

**Comment by kkjdroid** [comment]
OK, I found the solution when I read the config file more carefully. You want to use "%ROM_RAW%" (WITH quotes) on Windows because otherwise ES uses *NIX-style space escapes. Windows requires the quotes.

**Comment by Hancharenko** [comment]
For those who wish to launch Dolphin from the original installed location, you can also use the 8-character alias for Program Files and Program Files (x86).

```
    <system>
        <fullname>Nintendo GameCube</fullname>
        <name>gc</name>
        <path>D:\Nintendo GameCube</path>
        <extension>.iso .ISO</extension>
        <command>C:\Progra~1\Dolphin\Dolphin.exe /b /e "%ROM_RAW%"</command>
        <platform>gc</platform>
        <theme>gc</theme>
    </system>
```

**Comment by kkjdroid** [comment]
You should also be able to use "C:\Program Files (x86)\Dolphin\Dolphin.exe" /b /e "%ROM_RAW%". If you just quote everything that has a space, Windows usually behaves itself.

**Comment by dunderdotten** [comment]
I just add the emudirectory in Windows "Environment Variables" under "PATH" so  i can launch with commands like this:
<command>Dolphin.exe -e "%ROM_RAW%" -b</command>
