### ISSUE TITLE
Syntax error in Font.cpp

### ISSUE THREAD

**Issue by ldiro** [Aloshi/EmulationStation#397]
Hi,

I want to compile ES for windows, but i got a "syntax error" in visual studio in Font.cpp at line 801 :
```c++
cache->metrics = { sizeText(text, lineSpacing) };
```
I got those errors :
```
Error	12	error C2059: syntax error : '{'	D:\building\src\1de0b888aa\es-core\src\resources\Font.cpp	801	1	es-core
Error	13	error C2143: syntax error : missing ';' before '{'	D:\building\src\1de0b888aa\es-core\src\resources\Font.cpp	801	1	es-core
Error	14	error C2143: syntax error : missing ';' before '}'	D:\building\src\1de0b888aa\es-core\src\resources\Font.cpp	801	1	es-core
```
To fix I tried to uncomment line 797 :
```c++
TextCache::CacheMetrics metrics = { sizeText(text, lineSpacing) };
```
And changed line 801 :
```c++
cache->metrics;
```
With this, the compilation is OK in Visual Studio but i have a bug in ES. When I open the menu with the "start" button, the hover effect are not over the text. And ES crash everytime I push the "A" button and select a choice in the menu.

Did someone had this problem ? Does someone have an idea to fix this problem ?

Thanks :)

**Comment by Aloshi** [comment]
What version of Visual Studio are you using? I use VS 2013, and everything compiles fine.

You can try changing line 801 to:
```
cache->metrics.size = sizeText(text, lineSpacing);
```

**Comment by ldiro** [comment]
Hi,

I'm using VS2013 but the express version, maybe it has something to do with the problem ?

Anyway, i applied your fix and everything compiles fine now, thanks a lot ! Keep up the good work :)
