### ISSUE TITLE
Creating a launcher for another system

### ISSUE THREAD

**Issue by ChrisShire** [Aloshi/EmulationStation#403]
Hi there, amazing piece of software!

I'm trying to integrate it with Kodi. I have a launcher for Kodi to bring up emulationstation, but am struggling to get it to go the other way.

I would like emulationstation to actually close and then bring up Kodi if possible- I'm on a Windows machine and used an AutoIT script that I added as a "rom" to a "launchers' system. This, theoretically, just closes emulation station and then runs Kodi

....except it never gets that far! Emulation station does not quit, but pops back up again and Kodi remains unlaunched.

es_log looks like this;

lvl2: 	Attempting to launch game...
lvl2: 		C:/Users/LivingRoom/.emulationstation/roms/launchers/open\ kodi.exe
lvl1: 	...launch terminated with nonzero exit code 1!
lvl2: 	Creating surface...
lvl2: 	Created window successfully.
lvl2: 	Added known joystick Generic   USB  Joystick   (instance ID: 3, device index: 0)
lvl2: 	Added known joystick Generic   USB  Joystick   (instance ID: 2, device index: 1)
lvl2: 	Added known joystick Generic   USB  Joystick   (instance ID: 3, device index: 0)
lvl2: 	Added known joystick Generic   USB  Joystick   (instance ID: 2, device index: 1)

I'm rather stuck- would anyone be able to help?

Thanks!

**Comment by ChrisShire** [comment]
In addition, the relevant section of es_config looks like'

	<system>
		<fullname>Launchers</fullname>
		<name>Launchers</name>
		<path>~\.emulationstation\roms\launchers</path>
		<extension>.exe .EXE</extension>
		<command>%ROM%</command>
		<platform>pc</platform>
	</system>

**Comment by Aloshi** [comment]
Try changing the launch command to `"%ROM_RAW%"` (quotes included).

**Comment by ChrisShire** [comment]
Thanks dude, that did the trick!!
