### ISSUE TITLE
Background music during selection?

### ISSUE THREAD

**Issue by Skyrunner65** [Aloshi/EmulationStation#410]
How would I add background MUSIC for selection?
Just some music that can play in the background while I'm selecting a game.

 From what I know,
scrollSound is for when it scrolls, 
gameSelectSound is when you select a game,
backSound is when you go back,
and menuOpenSound is when a menu is opened.

**Comment by Enverex** [comment]
This is a duplicate of https://github.com/Aloshi/EmulationStation/issues/341
