### ISSUE TITLE
ES launching game issue

### ISSUE THREAD

**Issue by ChrisShire** [Aloshi/EmulationStation#411]
My apologies if this has been previously covered. I am using epsxe as my Playstation emulator (running on Win 7). When I launch the game it simply settles back to the emulationstation screen. I have checked es_log and run the command through the Run Command Windows option and it works fine, but does not work when launched from EmulationStation!

The relevant section of my es_systems.cfg is;
<system>
		<name>psx</name>
		<fullname>Sony Playstation</fullname>
		<path>~\.emulationstation\roms\psx</path>
		<extension>.bin .BIN .cue .CUE</extension>
		<command>"C:\Users\LivingRoom\Desktop\Emulation\ePSXe1925\ePSXe.exe" -nogui -loadbin "%ROM_RAW%"</command>
		<platform>psx</platform>
		<theme>psx</theme>
	</system>

and the output from es_log is;

lvl2: 	Attempting to launch game...
lvl2: 		"C:\Users\LivingRoom\Desktop\Emulation\ePSXe1925\ePSXe.exe" -nogui -loadbin "C:/Users/LivingRoom/.emulationstation/roms/psx/Tekken3.bin"
lvl1: 	...launch terminated with nonzero exit code 1!
lvl2: 	Creating surface...
lvl2: 	Created window successfully.

The command works fine from a Run Command, but just not when launching from emulationstation...I am puzzled! Can anyone help?

Thanks.

**Comment by ChrisShire** [comment]
solved it, just removed the quotes around the path to the emulator!

**Comment by JBluesword** [comment]
Thank you so much I been looking all over the internet for a fix 100% worked perfect. Works on Windows 8.1 <3

**Comment by tinesone** [comment]
Hmmmmm. it does not work. Maybe becouse i have a space in my name. What do i need to do? mmbv\ temp does not work?

**Comment by ninjaoxygen** [comment]
This issue can be solved by adding a second set of quotes to the entire command line, for example:
""C:\Users\LivingRoom\Desktop\Emulation\ePSXe1925\ePSXe.exe" -nogui -loadbin "%ROM_RAW%""

It is triggered by there being a quote at the beginning and end of the entire command line, one set is stripped automatically.

**Comment by AucardThe3rd** [comment]
i get the same issue, here is a section of my cfg

	<system>
		<name>nes</name>
		<fullname>Nintendo Entertainment System</fullname>
		<path>F:\roms\nes</path>
		<extension>.nes .NES</extension>
		<command>%HOMEPATH%\.emulationstation\systems\retroarch\retroarch.exe -L %HOMEPATH%\.emulationstation\systems\retroarch\cores\fceumm_libretro.dll "%ROM_RAW%"</command>
		<platform>nes</platform>
		<theme>nes</theme>	
	</system>

**Comment by ninjaoxygen** [comment]
I would be surprised if %HOMEPATH% alone works properly, it is missing the drivespec? Does %USERPROFILE% work instead?

Have you tried quoting all the paths and adding the extra sets of quotes to the <command> as suggested?

For example:
`<command>""%USERPROFILE%\.emulationstation\systems\retroarch\retroarch.exe" -L "%USERPROFILE%\.emulationstation\systems\retroarch\cores\fceumm_libretro.dll" "%ROM_RAW%""</command>`
