### ISSUE TITLE
Xbox controller not detected on SteamOS

### ISSUE THREAD

**Issue by sharkwouter** [Aloshi/EmulationStation#412]
Emulation Station doesn't respond to any of the buttons on my wireless Xbox 360 controller on SteamOS. This is on the welcome screen, so I can't configure the controller. When using a keyboard everything works like expected.

I compiled the version of Emulation Station in the git master a couple of minutes ago.

**Comment by Aloshi** [comment]
Hmm, try adding `<bool name="BackgroundJoystickInput" value="1" />` to your `$HOME/es_settings.cfg` and see if that helps at all.

**Comment by sharkwouter** [comment]
It took me a while to find the time to try this out, but I did now. I still get "NO GAMEPADS DETECTED".

**Comment by Enverex** [comment]
Silly question but does it work in other native games? (e.g. Super Meat Boy, etc).

**Comment by sharkwouter** [comment]
Yes, my controller works fine with other games and with Steam.

**Comment by sharkwouter** [comment]
This is no longer relevant. The old version of SteamOS hasn't been updated in years now.
