### ISSUE TITLE
Scraper doesn't always work correctly

### ISSUE THREAD

**Issue by nschloe** [Aloshi/EmulationStation#413]
I'm running EmulationStation through [RetroPie](http://blog.petrockblock.com/retropie/) and it works mostly smoothly. One papercut I found was that some quite popular games couldn't be scraped, e.g., the search string "turtles in time" for SNES finds nothing when it should find http://thegamesdb.net/game/188.

**Comment by Enverex** [comment]
It may be because it's too different to be seen as a valid result. What's the exact name of the ROM you have?

The game on TGDB is "Teenage Mutant Ninja Turtles IV: Turtles In Time" which is significantly different than just "Turtles in Time" if that's what your file is named.

**Comment by nschloe** [comment]
My file name is actually "Teenage Mutant Ninja Turtles IV: Turtles In Time", but I would argue that even when searching for only "Turtles in Time", the correct data should at least appear in the list of search results, just as it does when searching for it on the TGDB website.

When naming a file "Teenage Mutant Ninja Turtles IV: Turtles In Time", can you reproduce this?

**Comment by Enverex** [comment]
I wrote my own scraper and don't use the one inside EmulationStation (it was far too slow and basic, mine scrapes 10+ sites and does a massive amount of processing in comparison) so unfortunately I can't easily test this.

What I assume is the search URL (http://thegamesdb.net/api/GetGame.php?name=Teenage%20Mutant%20Ninja%20Turtles%20IV:%20Turtles%20In%20Time) does indeed pull the right result so I'm not sure where ES is getting stuck.

I'll see if I can recreate this somehow.

**Comment by nschloe** [comment]
> it was far too slow and basic, mine scrapes 10+ sites and does a massive amount of processing in 
> comparison

Wow, sounds great! Ever thought about putting it into EmulationStation?

**Comment by Enverex** [comment]
I'm still in the process of rewriting some of it as it's too specific to my own setup right now. It's around 3000 lines of code so it's a careful process.

It's not designed to be something everyone runs though, it populates a central database which others could then technically use. On my own (incomplete) collection it downloaded over 3GB of webpages (excluding images) for parsing, so you can imagine it would be a disaster if everyone's own installations were all trying to do that too!

**Comment by nilsbyte** [comment]
Better scraper support is one of the primary todos on the list. thegamesdb.net is often unreliable due to it's crappy API. It's not really in our hands, but we will try to add more scraper sources!
