### ISSUE TITLE
2.0.1 Scraper Crashing program

### ISSUE THREAD

**Issue by amigagamer** [Aloshi/EmulationStation#414]
Today i updated my win32 prebuilt binaries to 3/5/15 on the website frontpage.  I also built the latest 2.0.1 from the master branch on raspberryPI2.  Both versions seem to be crashing the software (segmentation fault) on using the scraper.

I have tried with my existing config, and also with a fresh install with just 1 system in es_systems.cfg
On RPI i build with 
cmake . -DCMAKE_CXX_COMPILER="g++-4.8" -DFREETYPE_INCLUDE_DIRS="/usr/include/freetype2/" 
My previous build with these settings worked perfectly

**Comment by Aloshi** [comment]
Reproduced, reverted download links to 2.0.0-rc1 for now since I don't have to fix it this morning. Expect a fix tonight.

**Comment by Aloshi** [comment]
Pushed a quick fix that hopefully fixed it. If it looks good I'll repackage 2.0.1 as 2.0.1a tonight.

**Comment by amigagamer** [comment]
Scraping seems to be working now from git:master thanks.  Only other major issue i could find with 2.0.1 is the Delete button on the scraper causes a crash...
 FileData.cpp:124 void FileData::removeChild(FileData*): Assertion 'false' failed

**Comment by Aloshi** [comment]
The delete thing has been a bug for a while. The unstable branch totally rewrote the FileData stuff, so it's probably fixed there.

**Comment by bloodroses75** [comment]
Just tried the win32 one via the zip file. I am reproducing the same issue with the scraping.

**Comment by Aloshi** [comment]
Should be fixed in the new 2.0.1a release.

**Comment by bloodroses75** [comment]
Works now. :) Even both scrapers work that didn't in RC1; although thearchive is insanely slow.

**Comment by amigagamer** [comment]
fixed in 2.0.1a , sorry forgot to close issue earlier
