### ISSUE TITLE
Dynamic gamelist.xml

### ISSUE THREAD

**Issue by vdutch** [Aloshi/EmulationStation#415]
Is it possible to have gamelist.xml associated with the theme we choose? I would like to have different gamelist.xml to match my themes, for example, if i have a dark theme i want my gamelist.xml to show white logos and if i choose the simple theme i want to have black logos. Is it possible? Am i missing something? Thanks in advance ;)

**Comment by nilsbyte** [comment]
The logos are part of the theme, if you want to have 'white logos' as you call it, you have to adjust the svg files in the 'dark theme' :) The gamelist.xml does not relate to this, it only holds the meta data for the games. Hope that helps.

**Comment by vdutch** [comment]
Thanks for the quick response ;) I think i wasn't clear in my request, i
should have said covers and not logos, i have some custom game covers for
black backgrounds, and others for white backgrounds, and i would like that
when i choose my dark theme the gamelist.xml would get the custom image for
dark backgrounds and when i choose the simple theme the gamelist.xml would
get the custom image for white backgrounds. Is that possible? Thanks in
advance and sorry for not being clear in my first request ;)
