### ISSUE TITLE
Sega/SegaCD Unknown Platform

### ISSUE THREAD

**Issue by brando56894** [Aloshi/EmulationStation#419]
What values should I be using? The ones listed in the help file don't seem to work. I've tried them lower case as listed in the readme file on here, also with them capitalized and underscored like they are in the header file, neither works.

lvl1: 	  Unknown platform for system "segacd" (platform ""SEGA_CD"" from list ""SEGA_CD"")
lvl1: 	  Unknown platform for system "genesis" (platform "SEGA_MEGA_DRIVE" from list "SEGA_MEGA_DRIVE")

	<system>
		<name>segacd</name>
		<fullname>Sega CD</fullname>
		<path>a:\roms\sega\cd\</path>
		<extension>.zip .iso</extension>
		<command>A:\Emulators\Fusion364\Fusion.exe %ROM%</command>
		<platform>SEGA_CD</platform>
		<theme>segacd</theme>
	</system>	
			
	<system>
		<name>genesis</name>
		<fullname>Sega Genesis</fullname>
		<path>a:\roms\sega\genesis\</path>
		<extension>.zip</extension>
		<command>A:\Emulators\Fusion364\Fusion.exe %ROM%</command>
		<platform>SEGA_MEGA_DRIVE</platform>
		<theme>megadrive</theme>
	</system>

listing them as "genesis, megadrive" doesn't work either.

**Comment by amigagamer** [comment]
should be using <platform>megadrive</platform>  in lowercase, same with segacd platform.

Im presuming your roms are all zipped?  if not add <extension>.zip .smd .bin .md</extension>

are you sure your emulators are installed on A: drive?  its rare to see A other than floppy disk drives!

**Comment by Enverex** [comment]
The correct names for all platforms can be found on this page - http://emulationstation.org/gettingstarted.html

If one doesn't exist for the system you're using, simply make one up.
