### ISSUE TITLE
Emulationstation freezes at reload

### ISSUE THREAD

**Issue by amm297** [Aloshi/EmulationStation#465]
I have two problems:

First: Emulationstation at any reboot demand me to configure a gamepad, even if i configure the keyboard yet

Second: Emulationstation freezes at come back of any rom

the es_log:

Configuring device -1 (Keyboard).
lvl2: 	  Mapping [Key Up] -> Up
lvl2: 	  Mapping [Key Down] -> Down
lvl2: 	  Mapping [Key Left] -> Left
lvl2: 	  Mapping [Key Right] -> Right
lvl2: 	  Mapping [Key Space] -> Start
lvl2: 	  Mapping [Key 5] -> Select
lvl2: 	  Mapping [Key Left Alt] -> A
lvl2: 	  Mapping [Key Left Ctrl] -> B
lvl2: 	  Mapping [Key C] -> X
lvl2: 	  Mapping [Key X] -> Y
lvl2: 	  Mapping [Key K] -> LeftBottom
lvl2: 	  Mapping [Key L] -> RightBottom
lvl2: 	  Mapping [Key I] -> LeftTop
lvl2: 	  Mapping [Key O] -> RightTop
lvl2: 	  Mapping [Key 1] -> LeftThumb
lvl2: 	  Mapping [Key 2] -> RightThumb
lvl2: 	  Mapping [Key 3] -> LeftAnalogUp
lvl2: 	  Mapping [Key 4] -> LeftAnalogDown
lvl2: 	  Mapping [Key 6] -> LeftAnalogLeft
lvl2: 	  Mapping [Key 7] -> LeftAnalogRight
lvl2: 	  Mapping [Key 8] -> RightAnalogUp
lvl2: 	  Mapping [Key 9] -> RightAnalogDown
lvl2: 	  Mapping [Key 0] -> RightAnalogLeft
lvl2: 	  Mapping [Key -] -> RightAnalogRight
lvl2: 		sudo /opt/retropie/supplementary/emulationstation/scripts/inputconfiguration.sh
lvl2: 	 req sound [basic.launch]
lvl2: 	   (missing)
lvl2: 	Attempting to launch game...
lvl2: 		sudo /home/pi/RetroPie-Setup/retropie_packages.sh retropiemenu launch /home/pi/RetroPie/retropiemenu/splashscreen.rp
lvl2: 	Creating surface...
lvl2: 	Created window successfully.

**Comment by thomasklein** [comment]
I have the same issue - Raspberry Pi 3, latest ES
