### ISSUE TITLE
ES takes ages to shutdown via F4 or "Quit ES" option

### ISSUE THREAD

**Issue by dankcushions** [Aloshi/EmulationStation#467]
Hi!

I'm using Retropie Beta 2 on a Raspberry Pi 2 (although I have run an apt-get update/upgrade a while ago so I may be running a later version - not sure how to check!). I'm not sure when this started happening, but it now takes exactly 1 minute 30 seconds from when I hit F4/shutdown, until the "Emulationstation will restart in 5 seconds" message comes up.

If I run 'top' it shows that ES is taking 100% CPU in this time. What is it doing during shutdown that could be taking all this time? The only possibly odd thing about my system is that I'm using ln -s to create symbolic links to rom folders in my USB stick, but I've opened permissions to that stick so it seems to have no problem saving gamelists, etc.

Other than that, it seems to function as usual - it's just the shutdowns.

Thanks,
Chris

**Comment by Lonecrowe** [comment]
Same here but it only started once I scraped everything.  So I think its unloading/loading / paging memory most likely and that is what slowed it down.  Without scraped data F4 quits fine.

**Comment by dankcushions** [comment]
I do have a lot of roms and everything scraped, so that makes sense! I wonder if it is possible to return to the shell whilst the unloading/cleanup processes are done in the background? Or at least show some sort of 'unloading' screen. Right now it just looks like it's hanging.

**Comment by Lonecrowe** [comment]
I'm going to redo mine with just the "thumbs" option.  I scraped full pics last time.  I guess if you use thumbs it performs better.

**Comment by dankcushions** [comment]
Mine is with thumbs only FYI...

**Comment by Lonecrowe** [comment]
Ok then there may be issues.  I'd log into the shell during the process with putty and watch top or the processes to see what is going on.  I wonder if these have iostat installed too..  Can watch to see what is happening when F4 is pressed.

**Comment by dankcushions** [comment]
Weirdly it only happens when F4 is pressed, or ES is exited - if it was just a cleanup process, I would expect it also to take a long time during a start > shutdown system, unless that somehow just terminates ES 'uncleanly'? This might might also explain why my ES metadata changes are unsaved (https://github.com/Aloshi/EmulationStation/issues/475) - perhaps I'll try and see if metadata changes ARE saved when I exit ES to bash, rather than a full system shutdown.

**Comment by desionalpha** [comment]
I am having this issue as well. I have yet to find a solution anywhere. Have any of you had any luck yet?

**Comment by dankcushions** [comment]
ES takes ages to shutdown with large game lists because it's compiling and writing huge XML files with all the game metadata. The only fix would be to change it use SQL or some other more efficient way of dealing with the database. For the former there is this issue: https://github.com/Aloshi/EmulationStation/issues/191 - so I will close this one as it is a duplicate.
