### ISSUE TITLE
EmulationStation and ssh

### ISSUE THREAD

**Issue by Nunardas** [Aloshi/EmulationStation#47]
So I want to start EmulationStation from ssh, not to play on my computer but on my tv. The thing is that i have two controllers and a Wifi dongle and i can't connect a keyboard. So my question is, can i through ssh tell my raspberry pi to start EmulationStation? The other reason that I would like to do this this way is because when i let EmulationStation connected to long it just freezes and i have to restart the whole machine.

Thank you

**Comment by rhew** [comment]
This works:
```
su -l pi -c emulationstation
```
