### ISSUE TITLE
[BUG] inputconfiguration.sh

### ISSUE THREAD

**Issue by trojanwarrior** [Aloshi/EmulationStation#516]
The script /opt/retropie/supplementary/emulationstation/scripts/inputconfiguration.sh has problems dealing with device names containing the character ' (apos). When ES starts detects my Thrustmaster Run'N' Drive gamepad all seems ok when I tried to configure it. But after launching any emulator, when emulators is closed and ES get the focus the gamepad stopped working and the only thin I can do is press F4 and close it. When ES restarts the input configuration starts again. 
In ~/.emulationstation/es_input.cfg there's an entry for this gamepad but no button nor axes configured for it. So I figured out what's going on. I plugged a Saitek Cyborg wired gamepad and everything is ok. Because the layout is almost the same for the Saitek and the Thrustmaster pads I copied the buttons and axes layout for the Thrustmaster from the Saitek and making sure the entry for the Thrustmaster has no ' character replacing it with the escape string &apos; and voilà, now is working with no problem.

So this is what I find out so far:

 1- ES starts and detects a new controller because there is no entry for the Run'n'drive gamepad in 
     ~/.emulationstation/es_input.cfg

 2- So it launchs the input configurator gui. I configure it and the gui writes    ~/.emulationstation/es_temporaryinput.cfg

 3- Then the script /opt/retropie/supplementary/emulationstation/scripts/inputconfiguration.sh is called and this script reads ~/.emulationstation/es_temporaryinput.cfg but it can not read it well because the apos ' on the device name. I supposed this script is responsible to write the final configuration for this pad at ~/.emulationstation/es_input.cfg but the only thing it can write is the entry for the pad but no button nor axes scheme.

The output of the inputconfiguration.sh:

 
Input type is 'joystick'.
Configuring 'emulationstation'
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless'])'
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='pagedown'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='pagedown'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='start'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='start'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='pageup'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='pageup'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='up'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='up'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='a'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='a'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='b'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='b'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='down'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='down'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='right'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='right'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='select'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='select'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid predicate: count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='left'])
compilation error: element with-param
XSLT-with-param: Failed to compile select expression 'count(/inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']/input[@name='left'])'
Invalid predicate: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Invalid expression: /inputList/inputConfig[@deviceName='Thrustmaster Run'N' Drive Wireless']
Configuring 'retroarch'
pi@retropie /opt/retropie/supplementary/emulationstation/scripts $

**Comment by Aloshi** [comment]
This is a bug with RetroPie's fork of ES. This version of EmulationStation doesn't do any input configuration.
