### ISSUE TITLE
Themes: add supporto for "hidden" tag or attribute to hide element

### ISSUE THREAD

**Issue by RigacciOrg** [Aloshi/EmulationStation#519]
I wish to hide some data from the detailed view, e.g. the md_lbl_rating and the md_rating. Removing the relevant section from the themes/simple/<system>/theme.xml does not work as I was thinking.

I am using ES Version 2.0.1a, from RetroPie 3.0 on Raspberry Pi 2.

**Comment by t3hi3x** [comment]
Hi - I wanted the same thing, so I implemented it. I've tested this on Mac OS (with an upstream patch) and Windows, and it works well.

https://github.com/t3hi3x/EmulationStation/commit/196d9175c38da86f778e6a1af4fc8abb09270eea

I plan on testing this in RPI as well, but I think RetroPie's ES is a fork, so I might have to merge this patch there.

**Comment by RigacciOrg** [comment]
The official way to hide some themable element is to place it outside of the screen, by setting its position at 200% of the screen size:

<pos>2 2</pos>
