### ISSUE TITLE
EmulationStation still running but hanged after exit emulator

### ISSUE THREAD

**Issue by Madcore** [Aloshi/EmulationStation#521]
I run EmulationStation and run a rom with no problem. But after exit the emulator, the command window is still open and EmulationStation doesn't show back. It's still running and I hace to kill the process. The log says:

lvl2: 	EmulationStation - v2.0.1a, built Mar  8 2015 - 16:10:39
lvl2: 	Creating surface...
lvl2: 	Created window successfully.
lvl2: 	Added known joystick XInput Controller #1 (instance ID: 0, device index: 0)
lvl2: 	Checking available OpenGL extensions...
lvl2: 	 ARB_texture_non_power_of_two: ok
lvl2: 	Loading system config file G:/Maca/Frontends/EmulationStation//.emulationstation/es_systems.cfg...
lvl2: 	 req sound [basic.launch]
lvl2: 	   (missing)

**Comment by RJRetro** [comment]
I'm going to assume your graphics are AMD.  They've had this issue reported in a couple other places.  Try updating to the latest AMD Catalyst beta driver.

**Comment by Madcore** [comment]
You're right. I have an AMD graphics card. I've updated to beta driver, and it fixed this issue. Sorry for bothering you with this.
