### ISSUE TITLE
Zoid Theme Freezes EmulationStation on RetroPie

### ISSUE THREAD

**Issue by Reev** [Aloshi/EmulationStation#529]
Hi,

i did a clean install of Retropie 3.2.1 (on a RPi2), expanded the Filesystem, allocated the GPU Memory, copied my ROM's and switched to the Zoid Theme.
After a full reboot (unplugged Power to move the Pi) the EmulationStation got stuck during boot. The Splashscreen appeared, then the Loading Screen of EmulationStation and after that it just went blank showing a white screen.
I could still connect via SSH. The Logfile did not show any significant errors.

After several hours of testing I managed to break it down to the SNES ROMS and the Zoid Theme. When I delete all SNES ROM's it works fine again. If I copy one SNES File (no matter which) it freezes again during the boot process. If I switch to another theme everything works fine again.

I did another clean install with the same result.

Can someone confirm this and/or give me a hint how to inspect further what is causing the Problem?

**Comment by digitalLumberjack** [comment]
Hi it is due to the memory used by the theme. If you activate many systems, the GPU memory used by  backgrounds images is too large for the reserved gpu memory of your rpi. If you are on rpi2, you can edit the config.txt to increase gpu memory. But that will only move the issue.

**Comment by Reev** [comment]
Hi, that makes sense. It loads the images in alphabetical order and since the snes is the last System i activated it is where it gets stuck.
I reserved 512MB of GPU Memory and only activated the Mega Drive/Genesis, SNES, Amiga and C64 Systems besides the standard Systems activated after the setup. If the already sufficiant to freeze the system the Zoid Theme shpuld probably be excluded or at least there should be a warning somewehere in the Theme installation screen.
