### ISSUE TITLE
Controller not working when starting game emulation

### ISSUE THREAD

**Issue by codemonkey1988** [Aloshi/EmulationStation#544]
I installed RetroPie 3.3 on my RaspberryPi Model B+. It comes with EmulationStation 2.0.1a.
As input device, I want to use a PS3 Controller with wired connection. I can configure the controller without any problems and it works in all menus. But when I start ja game, a message saying "PS3 Controller (1356/616) - not configured" shows up in the left bottom corner. The result is, that the controller does not work inside a game. I can only kill the task. This happens in all emulators.

I have attached the log from starting up the station to killing the retroarch-task.
Maybe this is a bug or I'm just missing some configuration. (Oh, I also installed the PS3 controller in RetroPie setup).
[EmulationStation_log.txt](https://github.com/Aloshi/EmulationStation/files/71024/EmulationStation_log.txt)

**Comment by codemonkey1988** [comment]
Oh, I forgot. When I use keyboard input, it works as expected.

**Comment by objectchris** [comment]
This is not an emulation station issue if the controller works in the emulation station menu fine - you should use the retropie forums for support on the controller issue.

**Comment by codemonkey1988** [comment]
Oh sorry for that. Then I will ask my question there. I was not sure, I that belongs to EmulationStation or to RetroPi. Never mind.
