### ISSUE TITLE
So with The Games DB Down is Emulationstation done.

### ISSUE THREAD

**Issue by Aaskari1988** [Aloshi/EmulationStation#564]
the other scraper never worked and sure covers could be done manually. but what about game info i see no easy way of getting that added now. i guess another source could be added but i haven't seen sign of live in development of this great front-end...

God im gonna have to use hyperspin :(

**Comment by objectchris** [comment]
https://github.com/Aloshi/EmulationStation/issues/563

**Comment by PFischbeck** [comment]
thegamesdb.net seems to be back up.
