### ISSUE TITLE
Really confused about control configuration / autoconfigration / ps3 pads

### ISSUE THREAD

**Issue by stuaxo** [Aloshi/EmulationStation#615]
Hi,
    I got ps3 pads working with emulationstation on Ubuntu 16.04.    I have no idea how to get retroarch and the other emulators to use these settings though.

Is there some way I can delete all their configs and start again ?

Retroarch seems to only have one core installed + use the keyboard. 

The PS3 Pad is listed in there, but I don't want to map buttons in all the emulators for all the systems if there is some way I can get default mappings for the pad and apply it to everything.

Sorry if this is the wrong place to ask !

**Comment by zigurana** [comment]
This problem is exactly what the Retropie team has solved. Have a look at
installing Retropie on existing unix based systems.

Op ma 26 sep. 2016 21:55 schreef Stuart Axon <notifications@github.com>:

**Comment by stuaxo** [comment]
Cool, I have installed retropie - but might have installed other packages.

I'm currently uninstalling all emulation based packages, trying to find all configs + delete.

Once I've got that, will re-run emulationstation ... having done that, it starts up and will ask me to configure joypads - if I do that, will those settings be propogated to the emulators (or should I be asking @ retropie ?)

**Comment by stuaxo** [comment]
Thanks, got joypads working - retroarch itself can be a bit confusing at times, but that's def not a question for here :)
