### ISSUE TITLE
Black version of the ES splashscreen

### ISSUE THREAD

**Issue by felleg** [Aloshi/EmulationStation#674]
Not really a bug, but I have no idea where else I could discuss this.
For the longest time I've been wondering if it's possible to change the background of the ES splashscreen from white to black so that it strains the eyes less when it boots. Is this possible at all right now? If not, what do the devs think of this idea?

Cheers.

**Comment by kaltinril** [comment]
@felleg If you update ES to the newest version you should notice it is now black.

**Comment by felleg** [comment]
Yup! I don't know if my request had anything to do with it, bit I noticed that some months ago and it looks awesome!
