### ISSUE TITLE
Assertion fail on launching game from EmulationStation menu

### ISSUE THREAD

**Issue by roadriverrail** [Aloshi/EmulationStation#739]
After having a lot of fun with my RetroPie, I decided to try installing EmulationStation by hand on my Ubuntu desktop.  I got pretty excited to launch a MAME rom, but got an assert failure as soon as I did:

emulationstation: /home/rhett/EmulationStation/es-core/src/resources/Font.cpp:536: void Font::renderTextCache(TextCache*): Assertion `*it->textureIdPtr != 0' failed.

**Comment by kgeoir** [comment]
Hello,
  This repo is dead, new one is here: https://github.com/RetroPie/EmulationStation

**Comment by dsx724** [comment]
@roadriverrail Did you get anywhere with this? Having some issues as well:
https://github.com/RetroPie/EmulationStation/issues/490

**Comment by roadriverrail** [comment]
Sorry, I did not, and I don't actually do much retro-gaming on my
workstation since I started using a dedicated RPi for it.
