### ISSUE TITLE
Help please: How to rotate a 16:9 90 deg *and* use 4:3 ratio (moved to top after rotation)?

### ISSUE THREAD

**Issue by jhudson8** [Aloshi/EmulationStation#744]
Hello, I'm building an arcade cabinet and would like to use a 16:9 TV for the screen but would like the viewable area to be 4:3.  Is it possible to rotate the TV 90 deg to view in portrait mode and use 4:3 aspect ratio (so a large black bar would appear at the (post rotated) bottom of the screen.

Thanks very much in advance.

Diagram (`X` represents hidden area to be covered up by arcade cabinet and whitespace is 4 x 3 menu and game viewable area)
```
_________________
|               |
|               |
|               |
|               |
|               |
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
|XXXXXXXXXXXXXXX|
```

**Comment by jhudson8** [comment]
In case anyone else wants to do this... you don't have to spend days trying to figure this out :)

Here are the steps (you can't use mame4all - move to at least libretro)

- Set splash screen
  - *UI* retropie setup > splash screens > choose splashscreen > Retropie splashscreens > retropie-2015-carbon-video-4x3.mp4

# make emulation station rotate and reposition
/opt/retropie/configs/all/autostart.sh
```
emulationstation --no-exit --screensize 810 1080 --screenoffset 0 0 --screenrotate 3 #auto
```

# make the games rotate and reposition
/opt/retropie/configs/all/retroarch.cfg
```
video_allow_rotate = true
video_rotation = 1
aspect_ratio_index = "22"
video_aspect_ratio_auto = false
custom_viewport_width = 810
custom_viewport_height = 1080
video_scale_integer = false
custom_viewport_x = 0
custom_viewport_y = 0
```

# remove boot logs (because they will be sideways)
/boot/cmdline.txt
```
dwc_otg.lpm_enable=0 console=serial0,115200 console=tty3 root=PARTUUID=f2d3cb4f-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait loglevel=3 consoleblank=0 plymouth.enable=0
vt.global_cursor_default=0
logo.nologo
quiet
```

# make your own splash screen with the image on the left 810 x 1080 and the rest black
put image in /home/pi/RetroPie/splashscreens/spash.jpg
pi config > rpsetup > configuration / tools > splashscreen > {select your spash screen}

# change game launch images (use the spash screen you made if you want)
https://github.com/retropie/retropie-setup/wiki/runcommand#adding-custom-launching-images
/opt/retropie/configs/SYSTEM_NAME/launching.jpg

**Comment by Phara0h** [comment]
Awesome I was hoping this was possible so I could get like a 43in tv but turn it into like a 20in 4:3 for a good price.
