### ISSUE TITLE
Round function - Eigen3 issue

### ISSUE THREAD

**Issue by xKZL** [Aloshi/EmulationStation#746]
Hello Guys,

I have an issue installing EmulationStation on my intel nuc with debian.

> In file included from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:9:0:
/home/nuc/EmulationStation/es-core/src/Util.h:18:22: error: ‘float round(float)’ conflicts with a previous declaration
 float round(float num);
                      ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/nuc/EmulationStation/es-core/src/Renderer.h:7,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:2:
/usr/include/c++/6/cmath:1790:3: note: previous declaration ‘constexpr float std::round(float)’
   round(float __x)
   ^~~~~
/home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp: In function ‘void Renderer::drawRect(float, float, float, float, unsigned int, GLenum, GLenum)’:
/home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:24: error: call of overloaded ‘round(float&)’ is ambiguous
   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
                        ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/string:38,
                 from /home/nuc/EmulationStation/es-core/src/platform.h:18,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:326:1: note: candidate: double round(double)
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
 ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/nuc/EmulationStation/es-core/src/Renderer.h:7,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:2:
/usr/include/c++/6/cmath:1794:3: note: candidate: constexpr long double std::round(long double)
   round(long double __x)
   ^~~~~
/usr/include/c++/6/cmath:1790:3: note: candidate: constexpr float std::round(float)
   round(float __x)
   ^~~~~
In file included from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:9:0:
/home/nuc/EmulationStation/es-core/src/Util.h:18:7: note: candidate: float round(float)
 float round(float num);
       ^~~~~
/home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:39: error: call of overloaded ‘round(float&)’ is ambiguous
   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
                                       ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/string:38,
                 from /home/nuc/EmulationStation/es-core/src/platform.h:18,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:326:1: note: candidate: double round(double)
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
 ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/nuc/EmulationStation/es-core/src/Renderer.h:7,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:2:
/usr/include/c++/6/cmath:1794:3: note: candidate: constexpr long double std::round(long double)
   round(long double __x)
   ^~~~~
/usr/include/c++/6/cmath:1790:3: note: candidate: constexpr float std::round(float)
   round(float __x)
   ^~~~~
In file included from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:9:0:
/home/nuc/EmulationStation/es-core/src/Util.h:18:7: note: candidate: float round(float)
 float round(float num);
       ^~~~~
/home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:54: error: call of overloaded ‘round(float&)’ is ambiguous
   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
                                                      ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/string:38,
                 from /home/nuc/EmulationStation/es-core/src/platform.h:18,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:326:1: note: candidate: double round(double)
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
 ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/nuc/EmulationStation/es-core/src/Renderer.h:7,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:2:
/usr/include/c++/6/cmath:1794:3: note: candidate: constexpr long double std::round(long double)
   round(long double __x)
   ^~~~~
/usr/include/c++/6/cmath:1790:3: note: candidate: constexpr float std::round(float)
   round(float __x)
   ^~~~~
In file included from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:9:0:
/home/nuc/EmulationStation/es-core/src/Util.h:18:7: note: candidate: float round(float)
 float round(float num);
       ^~~~~
/home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:69: error: call of overloaded ‘round(float&)’ is ambiguous
   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
                                                                     ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:507,
                 from /usr/include/c++/6/string:38,
                 from /home/nuc/EmulationStation/es-core/src/platform.h:18,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:326:1: note: candidate: double round(double)
 __MATHCALLX (round,, (_Mdouble_ __x), (__const__));
 ^
In file included from /usr/include/c++/6/complex:44:0,
                 from /usr/include/eigen3/Eigen/Core:80,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/nuc/EmulationStation/es-core/src/Renderer.h:7,
                 from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:2:
/usr/include/c++/6/cmath:1794:3: note: candidate: constexpr long double std::round(long double)
   round(long double __x)
   ^~~~~
/usr/include/c++/6/cmath:1790:3: note: candidate: constexpr float std::round(float)
   round(float __x)
   ^~~~~
In file included from /home/nuc/EmulationStation/es-core/src/Renderer_draw_gl.cpp:9:0:
/home/nuc/EmulationStation/es-core/src/Util.h:18:7: note: candidate: float round(float)
 float round(float num);
       ^~~~~

> 

It seems there is an issue with the round(float) function and the one from the Eigen3 library.
Any clue ?

**Comment by tforgione** [comment]
Is it the same bug than #692 ?

**Comment by mjkmoynihan** [comment]
just built successfully on Debian 9.4 2018-06-17 stretch lxqt using #692 suggestions
