### ISSUE TITLE
Retrogamingconsole.com unfairly possesses trademark to EmulationStation

### ISSUE THREAD

**Issue by AlexApps99** [Aloshi/EmulationStation#754]
@Aloshi @nilsbyte 

The guys at [retrogamingconsole.com](url) are selling products under the name "EmulationStation" without giving credit to the creators/community. It seems they own the trademark to EmulationStation, and sell RetroPie systems with no credit of programs used. I think that this is unfair and ridiculous and am asking that anybody that has experience in this to help out in stopping this stupid and blatant thievery. RetroPie has already succeeded in getting their rightfully owned trademark back, so why can't we?

**Please spread awareness of this company's mispractices, as they don't deserve customers, or the rights to EmulationStation.**

For more information on RetroPie's trademark problem, look on their blogpost here: [https://retropie.org.uk/2018/07/retropie-usa-trademark-resolved/](url).

**Comment by benbull** [comment]
To do this you'll need to engage a legal firm.  It depends on the territory retrogamingconsole.com are operating in as to how successful any outcome will be.  How do you know they own the trademark to EmulationStation?

**Comment by benbull** [comment]
They don't own a trademark in the UK territory (the area I'm familiar with); https://trademarks.ipo.gov.uk/

**Comment by benbull** [comment]
The don't own a trademark in US territory either that I can see from here; http://tmsearch.uspto.gov/

**Comment by benbull** [comment]
I would suggest that EmulationStation be registered in both territories as a formal trademark along with the logo, then a cease and desist letter is sent to retrogamingconsole.com.  However, as they're already breaching the IP of Nintendo, Sony, et. al. I would hazard a guess that they may not abide by it.

This the the firm retropie used; https://www.ecklandblando.com/

**Comment by benbull** [comment]
I've contacted EcklandBlando for some advice on how they could help based on the work they did for RetroPie.

**Comment by AlexApps99** [comment]
[retrogamingconsole.com](url)'s trademark registration no. is 5188292 in US territory.

**Comment by AlexApps99** [comment]
They still possess the trademark as seen here:
https://trademarks.justia.com/870/41/emulation-87041219.html
Note that it's `Emulation Station` as opposed to `EmulationStation`

**Comment by AlexApps99** [comment]
This issue has been open for over a year to no avail, will close it and somebody else can open an issue when more progress is made.
