### ISSUE TITLE
lvl10: TheGamesDBRequest - Error parsing XML, Start-end tags mismatch:

### ISSUE THREAD

**Issue by Hexoft** [Aloshi/EmulationStation#757]
As the title suggests rebooted my retropi and  the psx xml had become corrupted with nothing in despite having 7 games in there.
I tried to see if it could re-scrape but nothing.
Checked the system.cfg file ect.
but it looks fine just as all the others - 
"<system>
    <name>psx</name>
    <fullname>PlayStation</fullname>
    <path>/home/pi/RetroPie/roms/psx</path>
    <extension>.cue .cbn .img .iso .m3u .mdf .pbp .toc .z .znx .CUE .CBN .IMG .ISO .M3U .MDF .PBP .TOC .Z .ZNX</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ psx %ROM%</command>
    <platform>psx</platform>
    <theme>psx</theme>
  </system>
  <system>"

I'm really confused any help would be greatly appreciated!

**Comment by Hexoft** [comment]
![capture](https://user-images.githubusercontent.com/26858826/42727125-b9886242-8798-11e8-857e-04f008dc5921.PNG)

**Comment by Hexoft** [comment]
Apologise for being incompetence I checked the line to see the error but I still dont understand what part to change properly.
![capture2](https://user-images.githubusercontent.com/26858826/42727160-5b8004d8-8799-11e8-84f0-15212b97c1d3.PNG)

**Comment by Aloshi** [comment]
Merged https://github.com/Aloshi/EmulationStation/pull/761, which should fix this.
