### ISSUE TITLE
Suggestion: Allow copying of videos to a temp directory before playing

### ISSUE THREAD

**Issue by glindsey** [Aloshi/EmulationStation#760]
On my RetroPie system, I store game videos on a separate USB stick due to their size. However, sometimes the USB stick isn't capable of streaming video data fast enough for the player, resulting in corruption. It would be nice to have the ability to have ES copy the video data to a temporary location on the SD card before playing it.

This would obviously incur a delay, so I'd suggest themes display normal artwork while the copy is in progress, and then fade to the video when it is complete. You'd also need the copy to be capable of being halted while in progress so it doesn't slow down quick scrolling through the menu, so it'd probably have to run as an async job/task.

I realize this is a bit of a pie-in-the-sky suggestion, but I figured it's worth submitting.

**Comment by ghost** [comment]
Well, I’m an idiot; the corruption was due to trying to use VLC, which was maxing out the CPU and losing data. Switching to OMXPlayer fixed it. Closing.
