### ISSUE TITLE
ERROR! ERROR!! ERROR!

### ISSUE THREAD

**Issue by liaminventions** [Aloshi/EmulationStation#771]
When I try to run "./emulationstation" in terminal, I get the following errors:
      lv10:          Error creating SDL window!
                        Could not get EGL display
      lv10:          Renderer failed to initialize!
      lv10:          Window failed to initialize!
Also, I am running "./emulationstation" while it is selected onto the directery "/opt/retropie/supplementary/emulationstation"
I hope that I can get some help from you.

**Comment by ghost** [comment]
Do you try to compile EmulationStation in Raspbian or in RetroPie?

**Comment by liaminventions** [comment]
I forgot about this this thread and figured it out by myself and it works! I will close this thread.
