### ISSUE TITLE
[Feature] Add a commandline switch to disable audio

### ISSUE THREAD

**Issue by jazztickets** [Aloshi/EmulationStation#80]
I ran into a problem with mednafen where there was no audio because the device was busy. It was strange since i use ALSA with higan and that works fine. I ended up just using pulse with mednafen but it would be nice to be able to disable audio in emulationstation. A simple -noaudio flag would do just fine.

**Comment by Httqm** [comment]
For those landing here from Google, there is a workaround using [pasuspender](https://linux.die.net/man/1/pasuspender) :
`pasuspender -- [your mednafen command]`

source : https://askubuntu.com/questions/8425/how-to-temporarily-disable-pulseaudio
