### ISSUE TITLE
Freeze background with display mode change

### ISSUE THREAD

**Issue by MisterXYZ83** [Aloshi/EmulationStation#835]
Hello!

I'm building up a little arcade platform based on RetroPie system. I need to run ES with the default resolution of the display (for me 1600x1200 60Hz) but for certain emulators (like arcade ones) i would like to drop to a lower res (640x480 60Hz). I did it using the runcommand-onstart.sh to and runcommand-onend.sh to switch resolutions. It works but I have an issue; when i exit from a game and come back to ES i see the display with a freezed frame in transparency (the screen when i started the game) blended with the not-freezed real ES screen (responding to my inputs). 
I don't know if this is an issue of ES or other component of the system (video driver or others) but if i exit ES the display come back normally (no ghost frame in background).

What can i do?

I'm running RetroPie system from an Ubuntu X64 machine, not a retropie/raspberry setup.

**Comment by joolswills** [comment]
This repository is not used in RetroPie. For RetroPie support you should use the RetroPie Forum https://retropie.org.uk/forum/

**Comment by MisterXYZ83** [comment]
Thanks, i will ask there! sorry for disturbing
