### ISSUE TITLE
ES freezing without any input

### ISSUE THREAD

**Issue by petrockblog** [Aloshi/EmulationStation#87]
Hi Aloshi,

now I am also observing the freezing screen. I try to make this as structured and reproducible as possible to help debugging:

Issue description: ES freezes after about 45 minutes without any input. It is still possible to access the RPi via SSH. When killing the emulationstation process with the kill command, the black screen with the white dot stays on the screen.

System setup: Raspberry Pi, rev.1, 128/128 memory split, medium overclock-settings, RetroPie installation with a few ROMs within the ROMs folders

Kernel: Linux raspberrypi 3.6.11+ #474 PREEMPT Thu Jun 13 17:14:42 BST 2013 armv6l GNU/Linux

Since when: Pressumably after this commit: https://github.com/petrockblog/RetroPie-Setup/commit/74eb0afd1abc684ff1263223a04ba8fa9aaf1d75, but I am not 100% sure about this.

How to reproduce: Start Emulation Station and wait

Comments: 

The binaries-download of the RetroPie Script contains the "older" version of Emulation Station, which was compiled without CMake. <b>The described issue does NOT occur with that older version of Emulation Station!</b> The issue #79 might have the same issue.
A next step could be to see, if any input extends the time at which the system freezes.

**Comment by Perfect-Chaos** [comment]
Sorry to write on such an old issue but I seem to have exactly the same problem! After an idle timespan which seems like between 30 and 45 minutes Emulationstation seems to hang/freeze. I often stay in the SNES-Gamelist and switch the channel on my TV. After the told timespan I switch back to HDMI and the gamelist is still open... but Emulationstation is not responding to any input. But my Raspberry Pi is still connectable via ssh.
I found it really interesting that when I have killed the Emulationstation sub-process "/opt/retropie/supplementary/emulationstation/emulationstation" via ssh the TV-screen changes back to the shell to display the "After 5 Seconds Emulationstation restarts..."-Message. After 5 seconds the sub-process starts again normally but the TV-screen does not change whatsoever. It still shows the shell with the "After 5 Seconds Emulationstation restarts..."-Message. When I manually kill the sub-process while Emulationstation is not "freezing" everything starts normally after 5 seconds. So maybe it could have something to do with the X server? 
I really have not much experience with the Unix X server so this can be complete bullshit but maybe the information helps in any way :)
If I can help with further information please just tell me! I would really really like to have this issue fixed!
